### ISSUE TITLE
你好，请问这个屏的清屏命令是什么？

### ISSUE THREAD

**Issue by iggymayer** [hexesdesu/ESP32VFDClock#1]
RT

**Comment by hexesdesu** [comment]
我上传了一个名为PT6302_9.pdf的数据手册。不清楚你的目的是什么，我能想到两种解决方案，一种是写入八位的空格；另一种，你可以使用关闭显示命令，数据手册里“DISPLAY LIGHT SET COMMOND”部分有介绍。

**Comment by iggymayer** [comment]
谢谢
